In [3]:
import numpy as np

# 100个服从正态分布的随机数
arr1 = np.random.randn(10, 10)
arr1

array([[-1.18109719e+00, -7.46705285e-01, -3.49446281e-01,
         9.87735947e-02, -9.53226624e-01, -1.31150703e-01,
         1.08345499e+00, -2.89897027e-01,  8.24004209e-02,
         4.01738327e-01],
       [ 4.11434874e-01,  2.67642039e-01, -8.30390315e-01,
        -1.12048654e+00,  6.83899248e-01,  1.97314444e-01,
        -1.45313920e+00,  6.23840747e-01,  1.10880480e+00,
         8.97436274e-01],
       [ 1.21429320e+00,  2.13036582e+00,  1.01488948e+00,
        -1.05470097e+00, -1.24482699e+00, -1.54332336e-01,
         9.35953264e-01,  7.38453826e-01,  1.36133998e+00,
         9.96231516e-01],
       [ 2.57822689e-01,  9.42609099e-01,  5.59758009e-02,
         8.74553859e-02,  1.47792798e+00,  5.76313509e-01,
         2.96026718e+00,  1.93104928e+00,  1.65737586e-01,
         5.39256168e-01],
       [-1.65429049e-01,  3.75406385e-01, -1.25430143e+00,
         3.15108311e+00,  1.49689321e+00, -9.92171186e-01,
         1.87220482e-01, -7.35730830e-01, -5.04092361e-01,
         9.

In [4]:
# 四则运算
arr2 = np.zeros((3, 3))
arr3 = np.arange(1, 10).reshape(3, 3)

print(arr2 + arr3)
print(arr2 - arr3)
print(arr2 * arr3)
print(arr2 / arr3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 读取数据
data = np.genfromtxt('./dataFile/data.csv', delimiter=",", dtype=np.str, skip_header=1)
data

array([['0', '767', '33', ..., 'Initmates', 'Intimate', 'Intimates'],
       ['1', '1080', '34', ..., 'General', 'Dresses', 'Dresses'],
       ['2', '1077', '60', ..., 'General', 'Dresses', 'Dresses'],
       ...,
       ['23483', '1104', '31', ..., 'General Petite', 'Dresses',
        'Dresses'],
       ['23484', '1084', '28', ..., 'General', 'Dresses', 'Dresses'],
       ['23485', '1104', '52', ..., 'General Petite', 'Dresses',
        'Dresses']], dtype='<U14')

In [6]:
# 统计评论数大于 300 的数据
from collections import Counter
clothingID = data[:, 1]
comment = Counter(clothingID)
comSorted = dict(sorted(comment.items(), key=lambda k: k[1], reverse=True))
comAns = {k:v for k,v in comSorted.items() if v>300}
comAns

{'1078': 1024,
 '862': 806,
 '1094': 756,
 '1081': 582,
 '872': 545,
 '829': 527,
 '1110': 480,
 '868': 430,
 '895': 404,
 '936': 358,
 '867': 351,
 '850': 338,
 '1095': 327,
 '863': 306}

In [7]:
answer = []
for key in comAns.keys():
    ansItem = {}
    ansItem['Clothing-ID'] = key
    # 获取该物品类别。
    ansItem['class'] = data[clothingID == key, -1].astype(np.str)[0]

    # 计算评论数大于300的数据的受欢迎程度。
    popularData = data[clothingID == key, 4].astype(np.int)
    ansItem['popular'] = np.count_nonzero(popularData == 1) / comAns[key]

    # 总评论数
    ansItem['Total-Comment'] = comAns[key]
    
    # 统计在评论数大于300的数据中，对应评论者的年龄段分布
    ageData = data[clothingID == key, 2].astype(np.int)
    # 使用np.count_nonzero（）获得True的数量
    ansItem['Teenager'] = np.count_nonzero(ageData < 20)
    ansItem['Youth'] = np.count_nonzero((20 <= ageData) & (ageData < 40))
    ansItem['Middle-Age'] = np.count_nonzero((40 <= ageData) & (ageData < 60))
    ansItem['Elder'] = np.count_nonzero(60 <= ageData)

    answer.append(ansItem)


In [8]:
for ansItem in answer:
    print('在Clothing ID为' + ansItem['Clothing-ID'] + '的评论中，青少年评论数有' + str(ansItem['Teenager']) + '条，青年评论数有' + str(ansItem['Youth'])
     + '条，中年评论数有' + str(ansItem['Middle-Age']) + '条，老年评论数有' + str(ansItem['Elder']) + '条。')

在Clothing ID为1078的评论中，青少年评论数有2条，青年评论数有477条，中年评论数有444条，老年评论数有101条。
在Clothing ID为862的评论中，青少年评论数有0条，青年评论数有336条，中年评论数有373条，老年评论数有97条。
在Clothing ID为1094的评论中，青少年评论数有1条，青年评论数有389条，中年评论数有306条，老年评论数有60条。
在Clothing ID为1081的评论中，青少年评论数有1条，青年评论数有277条，中年评论数有243条，老年评论数有61条。
在Clothing ID为872的评论中，青少年评论数有1条，青年评论数有243条，中年评论数有226条，老年评论数有75条。
在Clothing ID为829的评论中，青少年评论数有0条，青年评论数有221条，中年评论数有226条，老年评论数有80条。
在Clothing ID为1110的评论中，青少年评论数有0条，青年评论数有224条，中年评论数有211条，老年评论数有45条。
在Clothing ID为868的评论中，青少年评论数有2条，青年评论数有189条，中年评论数有167条，老年评论数有72条。
在Clothing ID为895的评论中，青少年评论数有1条，青年评论数有163条，中年评论数有186条，老年评论数有54条。
在Clothing ID为936的评论中，青少年评论数有1条，青年评论数有157条，中年评论数有139条，老年评论数有61条。
在Clothing ID为867的评论中，青少年评论数有0条，青年评论数有160条，中年评论数有147条，老年评论数有44条。
在Clothing ID为850的评论中，青少年评论数有0条，青年评论数有142条，中年评论数有157条，老年评论数有39条。
在Clothing ID为1095的评论中，青少年评论数有2条，青年评论数有175条，中年评论数有119条，老年评论数有31条。
在Clothing ID为863的评论中，青少年评论数有0条，青年评论数有105条，中年评论数有135条，老年评论数有66条。


In [9]:
for ansItem in answer:
    print('Clothing ID: ' + str(ansItem['Clothing-ID']) + ', 受欢迎程度: ' + str(ansItem['popular']))

Clothing ID: 1078, 受欢迎程度: 0.8212890625
Clothing ID: 862, 受欢迎程度: 0.8200992555831266
Clothing ID: 1094, 受欢迎程度: 0.8214285714285714
Clothing ID: 1081, 受欢迎程度: 0.8487972508591065
Clothing ID: 872, 受欢迎程度: 0.8770642201834863
Clothing ID: 829, 受欢迎程度: 0.8273244781783681
Clothing ID: 1110, 受欢迎程度: 0.8395833333333333
Clothing ID: 868, 受欢迎程度: 0.7558139534883721
Clothing ID: 895, 受欢迎程度: 0.844059405940594
Clothing ID: 936, 受欢迎程度: 0.8212290502793296
Clothing ID: 867, 受欢迎程度: 0.811965811965812
Clothing ID: 850, 受欢迎程度: 0.8698224852071006
Clothing ID: 1095, 受欢迎程度: 0.7920489296636085
Clothing ID: 863, 受欢迎程度: 0.8496732026143791


In [10]:
saveData = [['ID', '类别', '受欢迎指数', '总评论数', '青少年评论数', '青年评论数', '中年评论数', '老年评论数']]
for ansItem in answer:
    saveItem = []
    for item in ansItem.values():
        saveItem.append(item)
    saveData.append(saveItem)
np.savetxt('save.csv', saveData, fmt="%s", delimiter=',', encoding='utf-8')

In [19]:
saveData1 = np.array(saveData[1:])
saveData1[saveData1[:, 3].astype(int) > 500]

array([['1078', 'Dresses', '0.8212890625', '1024', '2', '477', '444',
        '101'],
       ['862', 'Knits', '0.8200992555831266', '806', '0', '336', '373',
        '97'],
       ['1094', 'Dresses', '0.8214285714285714', '756', '1', '389',
        '306', '60'],
       ['1081', 'Dresses', '0.8487972508591065', '582', '1', '277',
        '243', '61'],
       ['872', 'Knits', '0.8770642201834863', '545', '1', '243', '226',
        '75'],
       ['829', 'Blouses', '0.8273244781783681', '527', '0', '221', '226',
        '80']], dtype='<U18')